### PR TITLE
Style edits

### PR DESCRIPTION
**Pull request by edwardloveall**
Here's a bunch of little style tweaks I wanted to change up:

* Updated logo with less faded letters and overall theme to match
* Added placeholder code to the demo section so people have something to play with as soon as they're on the site
* Removed the focus ring on language select box
* Set a min width for the site so it can't get too cramped, optimized for this new min width
* Tweaked the Pygment's copy a little so it fit visually with the others
* Gave the footer a little more breathing room
* Took advantage of bold and italic font styles for the rouge theme

### CODE REVIEW

**Comment by edwardloveall** [comment]
Checking on this. Didn't know if it got lost in the shuffle over the holidays.

**Comment by jneen** [comment]
Oh, sorry!  :+1:

**Comment by edwardloveall** [comment]
Awesome thanks!

**Comment by jneen** [comment]
Haha, thank *you*

**Pull request merged**
