### PR TITLE
Paste service

### PR DESCRIPTION
**Pull request by edwardloveall**
This adds the ability to save code from the homepage. When the user clicks the `Save this` button, it copies (using javascript) the contents of the code input into a hidden form field, then submits the form. Saved code, pastes, are accessed by a [hashid](http://hashids.org) instead of the standard id. This is to permit people from browsing around to other pastes.

Also:
* Updated the code theme to a modified version of [Tomorrow](https://github.com/chriskempson/tomorrow-theme)
* Added new, non-faded version of the logo
* Link header logo to homepage
* Fixed some cross browser issues for the homepage
* Use official version of the rouge gem from rubygems instead of github

### CODE REVIEW

**Comment by jneen** [comment]
I'm not able to start rails on this branch.  I get a `Hashids::SaltError`.  Is there something I need to configure?

**Comment by jneen** [comment]
Eh okay I figured that one out - now it's complaining about some delayed_job table?

**Comment by jneen** [comment]
...which isn't in schema.rb

**Comment by edwardloveall** [comment]
Ah that's a relic from my initial [suspenders](https://github.com/thoughtbot/suspenders/) install. Just removed it. The thing you need to set up is [dotenv](https://github.com/bkeepers/dotenv). Duplicate the `.sample.env` file to `.env` and add a value for `HASHIDS_SALT`. Any string will do.

**Comment by jneen** [comment]
Cool, I figured it out.  I'm partial to direnv myself :).

**Comment by jneen** [comment]
Awesome, looks good!  I think we could stand to fiddle with the colors a bit, but as far as functionality it's perfect.

**Comment by edwardloveall** [comment]
Oh interesting, never heard of direnv. Like dotenv but for your whole system instead of each individual project. Cool. What kind of color stuff are you thinking? For the code theme? The site in general?

**Comment by edwardloveall** [comment]
Actually, I'll merge this in and we should start an issue on it.

**Comment by jneen** [comment]
:+1:

**Comment by edwardloveall** [comment]
Would you mind starting the issue? You know what you'd like to change but I have no idea what to title it or write. :)

**Pull request merged**
