### PR TITLE
homepage: dynamically load the demo when changing language

### PR DESCRIPTION
**Pull request by jneen**
but only if the code hasn't been modified

### CODE REVIEW

**Comment by edwardloveall** [comment]
Dunno why this dropped off my radar. Looks good! I love that people can see the language snippet!

**Comment by Mogztter** [comment]
Can we merge this pull request? It would be really useful :wink:

**Comment by Mogztter** [comment]
@pyrmont do you have write access to this repository to merge this pull request? that would be awesome 😉

**Comment by pyrmont** [comment]
@Mogztter I do but I'm wondering if @jneen had a reason not to have merged it in back in 2017. I haven't set this repo up to run locally (it's on my list) so might just ping her and check that way. Sorry for the delay >_<

**Comment by Mogztter** [comment]
I don't know but the current behavior is really confusing (see my screencast: https://github.com/rouge-ruby/rouge.jneen.net/issues/35#issue-539514360).

>so might just ping her and check that way

Alright!

> Sorry for the delay >_<

No worries 😀

**Comment by ggrossetie** [comment]
> I have a rewrite of the site in Sinatra that's the subject of a PR in a new repo. You can see a version of this rewrite running on Heroku here.

@pyrmont It looks great! I also had a hard time understanding the Rails codebase :wink:

**Comment by pyrmont** [comment]
Closing this pull request as this version of the app has now been superseded by [the new dingus](https://github.com/rouge-ruby/dingus) (where this is a supported feature).

**Pull request closed without merging**
