### PR TITLE
Bump.ruby and rouge

### PR DESCRIPTION
**Pull request by jneen**
New versions all round

### CODE REVIEW

**Comment by edwardloveall** [comment]
Code looks good obviously, but why do we have merge conflicts? It looks like your branch has an ancestor from 11 months ago (e4e3ddf) but doesn't have any changes since then. Can you rebase onto master and push again?

**Comment by jneen** [comment]
ugh, yeah, working on that

**Comment by jneen** [comment]
aaalright, looks to be fixed - finally figured out how to run it locally to make sure it works with 2.x.

**Comment by edwardloveall** [comment]
Cool, looks good

**Pull request closed without merging**
